# Generated by Django 6.1.1 on 2026-09-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_target', models.CharField(choices=[('Introduction', 'Introduction'), ('Reintroduction', 'Reintroduction'), ('Practice', 'Practice'), ('Test', 'Test')], max_length=50)),
                ('exercise_type', models.CharField(blank=True, choices=[('Intro', 'Intro'), ('MultipleChoice', 'MultipleChoice'), ('TrueFalse', 'TrueFalse'), ('BuildBlock', 'BuildBlock'), ('FillInBlank', 'FillInBlank'), ('MatchPairs', 'MatchPairs'), ('TypeWord', 'TypeWord'), ('Crossword', 'Crossword'), ('ToneMarking', 'ToneMarking'), ('Speaking', 'Speaking'), ('Sketch', 'Sketch'), ('TextResponse', 'TextResponse'), ('ReadParagraph', 'ReadParagraph')], max_length=50, null=True)),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SlideConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('distractor', 'Distractor'), ('context', 'Context')], default='primary', max_length=50)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.construction')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_constructions', to='exercises.slide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SlideLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('distractor', 'Distractor'), ('context', 'Context')], default='primary', max_length=50)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.lexeme')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_lexemes', to='exercises.slide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
