# Generated by Django 6.0.5 on 2026-09-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_slideconstruction_slidelexeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='learning_target',
            field=models.CharField(blank=True, choices=[('Introduction', 'Introduction'), ('Reintroduction', 'Reintroduction'), ('Practice', 'Practice'), ('Test', 'Test')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('Intro', 'Intro'), ('MultipleChoice', 'MultipleChoice'), ('TrueFalse', 'TrueFalse'), ('BuildBlock', 'BuildBlock'), ('FillInBlank', 'FillInBlank'), ('MatchPairs', 'MatchPairs'), ('TypeWord', 'TypeWord'), ('Crossword', 'Crossword'), ('ToneMarking', 'ToneMarking'), ('Speaking', 'Speaking'), ('Sketch', 'Sketch'), ('TextResponse', 'TextResponse'), ('ReadParagraph', 'ReadParagraph')], default='Intro', max_length=50),
        ),
    ]
