# Generated by Django 6.0.5 on 2026-09-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_slide_learning_target_alter_slide_slide_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(blank=True, choices=[('Intro', 'Intro'), ('MultipleChoice', 'MultipleChoice'), ('TrueFalse', 'TrueFalse'), ('BuildBlock', 'BuildBlock'), ('FillInBlank', 'FillInBlank'), ('MatchPairs', 'MatchPairs'), ('TypeWord', 'TypeWord'), ('Crossword', 'Crossword'), ('ToneMarking', 'ToneMarking'), ('Speaking', 'Speaking'), ('Sketch', 'Sketch'), ('TextResponse', 'TextResponse'), ('ReadParagraph', 'ReadParagraph')], max_length=50, null=True),
        ),
    ]
