# Generated by Django 6.0.5 on 2026-09-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_slide_slide_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='slide_type',
            new_name='exercise_type',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='learning_target',
            new_name='pedagogical_role',
        ),
        migrations.AddField(
            model_name='slideconstruction',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('distractor', 'Distractor'), ('context', 'Context')], default='primary', max_length=50),
        ),
        migrations.AddField(
            model_name='slidelexeme',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('distractor', 'Distractor'), ('context', 'Context')], default='primary', max_length=50),
        ),
    ]
