# Generated by Django 6.1.1 on 2026-09-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_text', models.CharField(max_length=255)),
                ('normalized_text', models.TextField(max_length=255)),
                ('construction_type', models.CharField(choices=[('Idiom', 'Idiom'), ('Pattern', 'Pattern'), ('Phrase', 'Phrase'), ('Sentence', 'Sentence')], max_length=255)),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], db_index=True, null=True)),
                ('is_reviewable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_text', models.CharField(db_index=True, max_length=100)),
                ('normalized_text', models.CharField(db_index=True, max_length=100)),
                ('pos', models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJECTIVE', 'Adjective'), ('ADVERB', 'Adverb'), ('PREPOSITION', 'Preposition'), ('CONJUNCTION', 'Conjunction'), ('INTERJECTION', 'Interjection'), ('PRONOUN', 'Pronoun'), ('INTERROGATIVE', 'Interrogative'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('tone_pattern', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('frequency_rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('child_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_construction_components', to='vocabulary.construction')),
                ('parent_construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='vocabulary.construction')),
                ('lexeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vocabulary.lexeme')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.PositiveIntegerField()),
                ('end_index', models.PositiveIntegerField()),
                ('construction_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='vocabulary.constructioncomponent')),
            ],
        ),
        migrations.CreateModel(
            name='FlattenedConstructionLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexeme_index', to='vocabulary.construction')),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_index', to='vocabulary.lexeme')),
            ],
            options={
                'indexes': [models.Index(fields=['lexeme', 'construction'], name='vocabulary__lexeme__b3b1a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('construction', 'lexeme'), name='unique_construction_lexeme_index')],
            },
        ),
        migrations.AddConstraint(
            model_name='constructioncomponent',
            constraint=models.UniqueConstraint(fields=('parent_construction', 'position'), name='unique_component_position_per_construction'),
        ),
        migrations.AddConstraint(
            model_name='constructioncomponent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('child_construction__isnull', True), ('lexeme__isnull', False)), models.Q(('child_construction__isnull', False), ('lexeme__isnull', True)), _connector='OR'), name='component_xor_lexeme_or_construction'),
        ),
    ]
