# Generated by Django 6.0.5 on 2026-09-13 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexemevariant',
            name='lexeme',
        ),
        migrations.RemoveField(
            model_name='constructioncomponent',
            name='lexeme_variant',
        ),
        migrations.RemoveConstraint(
            model_name='constructionlexeme',
            name='unique_construction_lexeme_variant_index',
        ),
        migrations.RemoveIndex(
            model_name='constructionlexeme',
            name='vocabulary__lexeme__3707ec_idx',
        ),
        migrations.AlterField(
            model_name='construction',
            name='construction_type',
            field=models.CharField(choices=[('Idiom', 'Idiom'), ('Pattern', 'Pattern'), ('Phrase', 'Phrase'), ('Sentence', 'Sentence')], max_length=255),
        ),
        migrations.AlterField(
            model_name='constructioncomponent',
            name='child_construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_construction_components', to='vocabulary.construction'),
        ),
        migrations.AddConstraint(
            model_name='constructionlexeme',
            constraint=models.UniqueConstraint(fields=('construction', 'lexeme'), name='unique_construction_lexeme_index'),
        ),
        migrations.RemoveField(
            model_name='constructionlexeme',
            name='lexeme_variant',
        ),
        migrations.DeleteModel(
            name='LexemeVariant',
        ),
    ]
