# Generated by Django 6.0.5 on 2026-09-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_remove_lexemevariant_lexeme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lexeme',
            old_name='lemma',
            new_name='base_consonants',
        ),
        migrations.RenameField(
            model_name='lexeme',
            old_name='normalized_lemma',
            new_name='surface_form',
        ),
        migrations.AddField(
            model_name='lexeme',
            name='pos',
            field=models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJECTIVE', 'Adjective'), ('ADVERB', 'Adverb'), ('PREPOSITION', 'Preposition'), ('CONJUNCTION', 'Conjunction'), ('INTERJECTION', 'Interjection'), ('PRONOUN', 'Pronoun'), ('INTERROGATIVE', 'Interrogative'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
