# Generated by Django 6.0.5 on 2026-09-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_rename_lemma_lexeme_base_consonants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexeme',
            name='base_consonants',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lexeme',
            name='frequency_rank',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lexeme',
            name='pos',
            field=models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJECTIVE', 'Adjective'), ('ADVERB', 'Adverb'), ('PREPOSITION', 'Preposition'), ('CONJUNCTION', 'Conjunction'), ('INTERJECTION', 'Interjection'), ('PRONOUN', 'Pronoun'), ('INTERROGATIVE', 'Interrogative'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='lexeme',
            name='surface_form',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
