# Generated by Django 6.0.5 on 2026-09-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('in_review', 'In Review'), ('publishedPublished', 'Published'), ('archived', 'Archived')], default='draft', max_length=50),
        ),
    ]
