# Generated by Django 6.1.1 on 2026-09-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        ('users', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userlexemeprogress',
            name='lexeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.lexeme'),
        ),
        migrations.AddField(
            model_name='userlexemeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='userlexemeprogress',
            index=models.Index(fields=['user', 'due'], name='progress_us_user_id_f76c92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlexemeprogress',
            unique_together={('user', 'lexeme')},
        ),
    ]
